name: tagged-release

"on":
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  tagged-release:
    if: github.event.pull_request.merged
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}"
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.pull_request.title }}"
          prerelease: false
